# Generated by Django 4.2.1 on 2024-01-04 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "image",
                    models.ImageField(
                        default="artists/default.png", upload_to="artists"
                    ),
                ),
                ("bio", models.TextField(null=True, verbose_name="Artist Bio")),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("updated", models.DateField(auto_now=True)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        default="user.png",
                        force_format="JPEG",
                        keep_meta=True,
                        quality=75,
                        scale=0.5,
                        size=[400, 400],
                        upload_to="playlists/images/",
                        verbose_name="image",
                    ),
                ),
                ("updated", models.DateField(auto_now=True)),
                ("created", models.DateField(auto_now_add=True)),
                ("hide", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=300)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=11, verbose_name="Phone number")),
                ("subject", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        default="/userprofiles/user.png",
                        force_format="JPEG",
                        keep_meta=True,
                        quality=75,
                        scale=0.5,
                        size=[400, 400],
                        upload_to="songs/images/",
                    ),
                ),
                ("audio", models.FileField(upload_to="songs/audios/")),
                ("slug", models.SlugField(unique=True)),
                ("duration", models.IntegerField()),
                ("lyrics", models.TextField(blank=True, null=True)),
                ("listen_count", models.BigIntegerField(default=0)),
                ("updated", models.DateField(auto_now=True)),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "artists",
                    models.ManyToManyField(
                        default="", related_name="songs", to="core.artist"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="songs", to="core.genre"),
                ),
                (
                    "playlists",
                    models.ManyToManyField(
                        blank=True, related_name="songs", to="core.playlist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.song"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
