# Generated by Django 4.2.1 on 2024-01-04 21:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image",
            field=models.ImageField(
                default="/accounts/static/img/default.png", upload_to="artists"
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="/accounts/static/img/default.png",
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[400, 400],
                upload_to="playlists/images/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="artists",
            field=models.ManyToManyField(related_name="songs", to="core.artist"),
        ),
        migrations.AlterField(
            model_name="song",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="/accounts/static/img/musics.jpg",
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[400, 400],
                upload_to="songs/images/",
            ),
        ),
    ]
