# Generated by Django 4.2.1 on 2024-01-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_favoriteplaylist_favoritesong_likedplaylist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
