# Generated by Django 4.2.1 on 2024-01-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_artist_slug_alter_playlist_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="playlists",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="songs", to="core.playlist"
            ),
        ),
    ]
