# Generated by Django 4.2.1 on 2024-01-09 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0014_alter_artist_image_alter_playlist_image_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoriteplaylist",
            unique_together={("user", "playlist")},
        ),
        migrations.AlterUniqueTogether(
            name="favoritesong",
            unique_together={("user", "song")},
        ),
        migrations.AlterUniqueTogether(
            name="likedsong",
            unique_together={("user", "song")},
        ),
        migrations.DeleteModel(
            name="LikedPlaylist",
        ),
    ]
