# Generated by Django 4.2.1 on 2024-01-09 19:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                default="artists/default.png",
                force_format="JPEG",
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[800, 800],
                upload_to="artists",
            ),
        ),
    ]
