# Generated by Django 4.2.1 on 2024-01-06 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_phone_alter_user_photo"),
        ("accounts", "0005_alter_user_phone_alter_user_photo"),
    ]

    operations = []
