# Generated by Django 4.2.1 on 2024-01-06 15:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_merge_20240106_1901"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                crop=[400, 400],
                default="user.png",
                force_format="JPEG",
                keep_meta=True,
                quality=75,
                scale=0.5,
                size=[400, 400],
                upload_to="user-profiles",
                verbose_name="Image",
            ),
        ),
    ]
